In [36]:
import numpy as np

In [37]:
a = 10 
b = 20 

In [38]:
a+b

30

In [39]:
# 1D array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [40]:
# 2d array 
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [41]:
# get dimensions 
print(arr.ndim)
print(arr2.ndim)

1
2


In [42]:
# get shape
print( arr.shape)
print(arr2.shape)

(5,)
(2, 4)


In [43]:
# get type 
arr2.dtype

dtype('int32')

In [49]:
# get size
print(arr.itemsize) # gives memory size of one element of that array
print(arr2.size) # will give no pf elements in array
print( arr.size * arr.itemsize) # to get total memory occupy by that array
# another way for total size
print(arr2.nbytes)

4
8
20
32


In [51]:
# we can change dtype of an array
arr = np.array([1,2,3,4,5,6,7] , dtype = 'int16')
arr.dtype

dtype('int16')

In [52]:
# accessing / changing specific elements , rows , columns etc.
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a.shape)
print(a)

(2, 7)
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [54]:
# a specific element 
a[1,4]

12

In [55]:
# negative indexing also works 
a [1,-3]

12

In [57]:
# a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [58]:
# a specific column
a[:,4]

array([ 5, 12])

In [60]:
# more complicated (start idx : end idx : steps)
a[0,1:6:2]

array([2, 4, 6])

In [62]:
# to change value just assign value after accessing them 
# value will be changed , for e.g 
a[1,3] = 0
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10  0 12 13 14]]


In [63]:
# 3D array

In [64]:
b = np.array([ [[1,2],[3,4]] , [[5,6],[7,8]] ])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [65]:
# lets access value = 5 
b[1,0,0]

5

In [66]:
b[0,:,:] = [ [9,9] ,[9,9] ]
b

array([[[9, 9],
        [9, 9]],

       [[5, 6],
        [7, 8]]])